//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ayadi.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ayadi.Localization.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string adress_ {
            get {
                return ResourceManager.GetString("adress_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string birthday_ {
            get {
                return ResourceManager.GetString("birthday_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number.
        /// </summary>
        public static string buildingNumber_ {
            get {
                return ResourceManager.GetString("buildingNumber_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel_ {
            get {
                return ResourceManager.GetString("cancel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled!.
        /// </summary>
        public static string cancelled_ {
            get {
                return ResourceManager.GetString("cancelled_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string CartViewModel_cart {
            get {
                return ResourceManager.GetString("CartViewModel.cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Is Empty !.
        /// </summary>
        public static string CartViewModel_EmpatyMsg {
            get {
                return ResourceManager.GetString("CartViewModel.EmpatyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product(s) In Cart.
        /// </summary>
        public static string CartViewModel_inCart {
            get {
                return ResourceManager.GetString("CartViewModel.inCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CartViewModel_no {
            get {
                return ResourceManager.GetString("CartViewModel.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string CartViewModel_pay {
            get {
                return ResourceManager.GetString("CartViewModel.pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        public static string CartViewModel_sar {
            get {
                return ResourceManager.GetString("CartViewModel.sar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string CartViewModel_total {
            get {
                return ResourceManager.GetString("CartViewModel.total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CartViewModel_yes {
            get {
                return ResourceManager.GetString("CartViewModel.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string changePassword_ {
            get {
                return ResourceManager.GetString("changePassword_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password !.
        /// </summary>
        public static string ChangPasswordViewModel_enterNewPassword {
            get {
                return ResourceManager.GetString("ChangPasswordViewModel.enterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Old Password !.
        /// </summary>
        public static string ChangPasswordViewModel_enterOldPaswword {
            get {
                return ResourceManager.GetString("ChangPasswordViewModel.enterOldPaswword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ChangPasswordViewModel_newPassword {
            get {
                return ResourceManager.GetString("ChangPasswordViewModel.newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string ChangPasswordViewModel_oldPaswword {
            get {
                return ResourceManager.GetString("ChangPasswordViewModel.oldPaswword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password has been changed successfully.
        /// </summary>
        public static string ChangPasswordViewModel_passwordChanged {
            get {
                return ResourceManager.GetString("ChangPasswordViewModel.passwordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password has been not changed !.
        /// </summary>
        public static string ChangPasswordViewModel_passwordNotChanged {
            get {
                return ResourceManager.GetString("ChangPasswordViewModel.passwordNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype New Password.
        /// </summary>
        public static string ChangPasswordViewModel_retype_NewPassword {
            get {
                return ResourceManager.GetString("ChangPasswordViewModel.retype NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Address.
        /// </summary>
        public static string CheckoutAdressViewModel_addAdress {
            get {
                return ResourceManager.GetString("CheckoutAdressViewModel.addAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string CheckoutAdressViewModel_adresses {
            get {
                return ResourceManager.GetString("CheckoutAdressViewModel.adresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose address.
        /// </summary>
        public static string CheckoutAdressViewModel_chooseAdress {
            get {
                return ResourceManager.GetString("CheckoutAdressViewModel.chooseAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Billing Address.
        /// </summary>
        public static string CheckoutAdressViewModel_SelectBillAdress {
            get {
                return ResourceManager.GetString("CheckoutAdressViewModel.SelectBillAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Shipping Address.
        /// </summary>
        public static string CheckoutAdressViewModel_SelectShipAdress {
            get {
                return ResourceManager.GetString("CheckoutAdressViewModel.SelectShipAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Method.
        /// </summary>
        public static string CheckoutAdressViewModel_shipMethod {
            get {
                return ResourceManager.GetString("CheckoutAdressViewModel.shipMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship to same address.
        /// </summary>
        public static string CheckoutAdressViewModel_shipToSamAdress {
            get {
                return ResourceManager.GetString("CheckoutAdressViewModel.shipToSamAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string CheckoutPaymentViewModel_payment {
            get {
                return ResourceManager.GetString("CheckoutPaymentViewModel.payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Payment Method.
        /// </summary>
        public static string CheckoutPaymentViewModel_SelectPaymentMethod {
            get {
                return ResourceManager.GetString("CheckoutPaymentViewModel.SelectPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string CheckoutPaymentViewModel_summary {
            get {
                return ResourceManager.GetString("CheckoutPaymentViewModel.summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string CheckoutShippingViewModel_paymentMethod {
            get {
                return ResourceManager.GetString("CheckoutShippingViewModel.paymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Shipping Method.
        /// </summary>
        public static string CheckoutShippingViewModel_SelectShippingMethod {
            get {
                return ResourceManager.GetString("CheckoutShippingViewModel.SelectShippingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string CheckoutShippingViewModel_shipping {
            get {
                return ResourceManager.GetString("CheckoutShippingViewModel.shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing  Address.
        /// </summary>
        public static string CheckoutSummaryViewModel_billingAdress {
            get {
                return ResourceManager.GetString("CheckoutSummaryViewModel.billingAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM.
        /// </summary>
        public static string CheckoutSummaryViewModel_confirm {
            get {
                return ResourceManager.GetString("CheckoutSummaryViewModel.confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order completed  successfully.
        /// </summary>
        public static string CheckoutSummaryViewModel_orderComplet {
            get {
                return ResourceManager.GetString("CheckoutSummaryViewModel.orderComplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not completed !.
        /// </summary>
        public static string CheckoutSummaryViewModel_orderNotComplet {
            get {
                return ResourceManager.GetString("CheckoutSummaryViewModel.orderNotComplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method Fees.
        /// </summary>
        public static string CheckoutSummaryViewModel_paymentMethodFess {
            get {
                return ResourceManager.GetString("CheckoutSummaryViewModel.paymentMethodFess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string CheckoutSummaryViewModel_products {
            get {
                return ResourceManager.GetString("CheckoutSummaryViewModel.products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string CheckoutSummaryViewModel_shippngAdress {
            get {
                return ResourceManager.GetString("CheckoutSummaryViewModel.shippngAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string CheckoutSummaryViewModel_subtotal {
            get {
                return ResourceManager.GetString("CheckoutSummaryViewModel.subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string CheckoutSummaryViewModel_summary {
            get {
                return ResourceManager.GetString("CheckoutSummaryViewModel.summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Payment Method !.
        /// </summary>
        public static string ChoosePaymentMethod_ {
            get {
                return ResourceManager.GetString("ChoosePaymentMethod_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city_ {
            get {
                return ResourceManager.GetString("city_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company_ {
            get {
                return ResourceManager.GetString("company_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string confirmDelete_ {
            get {
                return ResourceManager.GetString("confirmDelete_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country_ {
            get {
                return ResourceManager.GetString("country_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Saved !.
        /// </summary>
        public static string dataNotSavedMsg_ {
            get {
                return ResourceManager.GetString("dataNotSavedMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfully.
        /// </summary>
        public static string dataSavedMsg_ {
            get {
                return ResourceManager.GetString("dataSavedMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted!.
        /// </summary>
        public static string deleted_ {
            get {
                return ResourceManager.GetString("deleted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Delete.
        /// </summary>
        public static string deleteMsg_ {
            get {
                return ResourceManager.GetString("deleteMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email_ {
            get {
                return ResourceManager.GetString("email_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Birthday !.
        /// </summary>
        public static string enterBirthDayMsg_ {
            get {
                return ResourceManager.GetString("enterBirthDayMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email !.
        /// </summary>
        public static string enterEmailMsg_ {
            get {
                return ResourceManager.GetString("enterEmailMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name !.
        /// </summary>
        public static string enterFistNameMsg_ {
            get {
                return ResourceManager.GetString("enterFistNameMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Gender!.
        /// </summary>
        public static string enterGenderMsg_ {
            get {
                return ResourceManager.GetString("enterGenderMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Name !.
        /// </summary>
        public static string enterLastNameMsg_ {
            get {
                return ResourceManager.GetString("enterLastNameMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password !.
        /// </summary>
        public static string enterPasswordMsg_ {
            get {
                return ResourceManager.GetString("enterPasswordMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Email !.
        /// </summary>
        public static string enterValidEmailMsg_ {
            get {
                return ResourceManager.GetString("enterValidEmailMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        public static string FavouriteViewModel_currency {
            get {
                return ResourceManager.GetString("FavouriteViewModel.currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        public static string FavouriteViewModel_favourite {
            get {
                return ResourceManager.GetString("FavouriteViewModel.favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string female_ {
            get {
                return ResourceManager.GetString("female_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string FillteringViewModel_categoris {
            get {
                return ResourceManager.GetString("FillteringViewModel.categoris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstName_ {
            get {
                return ResourceManager.GetString("firstName_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender_ {
            get {
                return ResourceManager.GetString("gender_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit back again to Exit.
        /// </summary>
        public static string hitBackToExit_ {
            get {
                return ResourceManager.GetString("hitBackToExit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string HomeViewModel_categories {
            get {
                return ResourceManager.GetString("HomeViewModel.categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeViewModel_home {
            get {
                return ResourceManager.GetString("HomeViewModel.home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string HomeViewModel_myAcount {
            get {
                return ResourceManager.GetString("HomeViewModel.myAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HomeViewModel_settings {
            get {
                return ResourceManager.GetString("HomeViewModel.settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stors.
        /// </summary>
        public static string HomeViewModel_stors {
            get {
                return ResourceManager.GetString("HomeViewModel.stors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastName_ {
            get {
                return ResourceManager.GetString("lastName_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed !.
        /// </summary>
        public static string loginFaildMsg_ {
            get {
                return ResourceManager.GetString("loginFaildMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string LoginViewModel_facebook {
            get {
                return ResourceManager.GetString("LoginViewModel.facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password ?.
        /// </summary>
        public static string LoginViewModel_forgetPassword {
            get {
                return ResourceManager.GetString("LoginViewModel.forgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string LoginViewModel_google {
            get {
                return ResourceManager.GetString("LoginViewModel.google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginViewModel_login {
            get {
                return ResourceManager.GetString("LoginViewModel.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string LoginViewModel_or {
            get {
                return ResourceManager.GetString("LoginViewModel.or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string LoginViewModel_signup {
            get {
                return ResourceManager.GetString("LoginViewModel.signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string LoginViewModel_twitter {
            get {
                return ResourceManager.GetString("LoginViewModel.twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string male_ {
            get {
                return ResourceManager.GetString("male_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet available.
        /// </summary>
        public static string noInterner_ {
            get {
                return ResourceManager.GetString("noInterner_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok_ {
            get {
                return ResourceManager.GetString("ok_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrdersViewModel_orders {
            get {
                return ResourceManager.GetString("OrdersViewModel.orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status.
        /// </summary>
        public static string OrdersViewModel_orderStatus {
            get {
                return ResourceManager.GetString("OrdersViewModel.orderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string OrdersViewModel_orderTotal {
            get {
                return ResourceManager.GetString("OrdersViewModel.orderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Status.
        /// </summary>
        public static string OrdersViewModel_paymentStatus {
            get {
                return ResourceManager.GetString("OrdersViewModel.paymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping status.
        /// </summary>
        public static string OrdersViewModel_shippingStatus {
            get {
                return ResourceManager.GetString("OrdersViewModel.shippingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password_ {
            get {
                return ResourceManager.GetString("password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords Not Matched !.
        /// </summary>
        public static string passwordNotMatchMsg_ {
            get {
                return ResourceManager.GetString("passwordNotMatchMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT.
        /// </summary>
        public static string payment_ {
            get {
                return ResourceManager.GetString("payment_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phoneNumber_ {
            get {
                return ResourceManager.GetString("phoneNumber_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Reviews yet !.
        /// </summary>
        public static string ProductsReviewsViewModel_noReviewsYet {
            get {
                return ResourceManager.GetString("ProductsReviewsViewModel.noReviewsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string ProductsReviewViewModel_bad {
            get {
                return ResourceManager.GetString("ProductsReviewViewModel.bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ProductsReviewViewModel_comment {
            get {
                return ResourceManager.GetString("ProductsReviewViewModel.comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ProductsReviewViewModel_done {
            get {
                return ResourceManager.GetString("ProductsReviewViewModel.done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send review.
        /// </summary>
        public static string ProductsReviewViewModel_fail {
            get {
                return ResourceManager.GetString("ProductsReviewViewModel.fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string ProductsReviewViewModel_good {
            get {
                return ResourceManager.GetString("ProductsReviewViewModel.good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Like it.
        /// </summary>
        public static string ProductsReviewViewModel_iLike {
            get {
                return ResourceManager.GetString("ProductsReviewViewModel.iLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Love it.
        /// </summary>
        public static string ProductsReviewViewModel_iLove {
            get {
                return ResourceManager.GetString("ProductsReviewViewModel.iLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make review.
        /// </summary>
        public static string ProductsReviewViewModel_makeRate {
            get {
                return ResourceManager.GetString("ProductsReviewViewModel.makeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Good.
        /// </summary>
        public static string ProductsReviewViewModel_notGoog {
            get {
                return ResourceManager.GetString("ProductsReviewViewModel.notGoog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string ProductsReviewViewModel_rate {
            get {
                return ResourceManager.GetString("ProductsReviewViewModel.rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        public static string ProductViewModel_addToCart {
            get {
                return ResourceManager.GetString("ProductViewModel.addToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment(s).
        /// </summary>
        public static string ProductViewModel_comment {
            get {
                return ResourceManager.GetString("ProductViewModel.comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Account.
        /// </summary>
        public static string RecoverAccountViewModel_recover {
            get {
                return ResourceManager.GetString("RecoverAccountViewModel.recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovering completed , Activation code has been sent , please check your Inbox.
        /// </summary>
        public static string RecoverAccountViewModel_recoverdMsg {
            get {
                return ResourceManager.GetString("RecoverAccountViewModel.recoverdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account related to this Email !.
        /// </summary>
        public static string RecoverAccountViewModel_unRecoverdMsg {
            get {
                return ResourceManager.GetString("RecoverAccountViewModel.unRecoverdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Retype Password.
        /// </summary>
        public static string retypePassword_ {
            get {
                return ResourceManager.GetString("retypePassword_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want To Delete This Product From Cart.
        /// </summary>
        public static string ruSure_ {
            get {
                return ResourceManager.GetString("ruSure_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save_ {
            get {
                return ResourceManager.GetString("save_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string SearchViewModel_Cat {
            get {
                return ResourceManager.GetString("SearchViewModel.Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string SearchViewModel_PriceFrom {
            get {
                return ResourceManager.GetString("SearchViewModel.PriceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string SearchViewModel_PriceTo {
            get {
                return ResourceManager.GetString("SearchViewModel.PriceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchViewModel_Search {
            get {
                return ResourceManager.GetString("SearchViewModel.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Word.
        /// </summary>
        public static string SearchViewModel_SearchWord {
            get {
                return ResourceManager.GetString("SearchViewModel.SearchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string SearchViewModel_Store {
            get {
                return ResourceManager.GetString("SearchViewModel.Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City !.
        /// </summary>
        public static string selectCityMsg_ {
            get {
                return ResourceManager.GetString("selectCityMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string SettingViewModel_aboutUs {
            get {
                return ResourceManager.GetString("SettingViewModel.aboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose language.
        /// </summary>
        public static string SettingViewModel_choseLang {
            get {
                return ResourceManager.GetString("SettingViewModel.choseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact US.
        /// </summary>
        public static string SettingViewModel_contactUs {
            get {
                return ResourceManager.GetString("SettingViewModel.contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Restart App Now ?.
        /// </summary>
        public static string SettingViewModel_restartApp {
            get {
                return ResourceManager.GetString("SettingViewModel.restartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Use.
        /// </summary>
        public static string SettingViewModel_termesOfUse {
            get {
                return ResourceManager.GetString("SettingViewModel.termesOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SettingViewModel_test {
            get {
                return ResourceManager.GetString("SettingViewModel.test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIPPING.
        /// </summary>
        public static string shiipping_ {
            get {
                return ResourceManager.GetString("shiipping_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Must Be More than 6 characters !.
        /// </summary>
        public static string shortPasswordMsg_ {
            get {
                return ResourceManager.GetString("shortPasswordMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup Failed !.
        /// </summary>
        public static string signupFaildMsg_ {
            get {
                return ResourceManager.GetString("signupFaildMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation link has been sent to your Email.
        /// </summary>
        public static string signupSucsessMsg_ {
            get {
                return ResourceManager.GetString("signupSucsessMsg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string SignupViewModel_signup {
            get {
                return ResourceManager.GetString("SignupViewModel.signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string SortingViewModel_grid {
            get {
                return ResourceManager.GetString("SortingViewModel.grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string SortingViewModel_lastUpdate {
            get {
                return ResourceManager.GetString("SortingViewModel.lastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string SortingViewModel_list {
            get {
                return ResourceManager.GetString("SortingViewModel.list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name A to Z.
        /// </summary>
        public static string SortingViewModel_nameAZ {
            get {
                return ResourceManager.GetString("SortingViewModel.nameAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Z to A.
        /// </summary>
        public static string SortingViewModel_nameZA {
            get {
                return ResourceManager.GetString("SortingViewModel.nameZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string SortingViewModel_position {
            get {
                return ResourceManager.GetString("SortingViewModel.position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price High to Low.
        /// </summary>
        public static string SortingViewModel_priceHL {
            get {
                return ResourceManager.GetString("SortingViewModel.priceHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Low to High.
        /// </summary>
        public static string SortingViewModel_priceLH {
            get {
                return ResourceManager.GetString("SortingViewModel.priceLH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortingViewModel_sortBy {
            get {
                return ResourceManager.GetString("SortingViewModel.sortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View As.
        /// </summary>
        public static string SortingViewModel_ViewAs {
            get {
                return ResourceManager.GetString("SortingViewModel.ViewAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name, Number.
        /// </summary>
        public static string StreentNameNumber_ {
            get {
                return ResourceManager.GetString("StreentNameNumber_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string SubHomeViewModel_categores {
            get {
                return ResourceManager.GetString("SubHomeViewModel.categores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string SubHomeViewModel_prodcuts {
            get {
                return ResourceManager.GetString("SubHomeViewModel.prodcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string SubHomeViewModel_showAll {
            get {
                return ResourceManager.GetString("SubHomeViewModel.showAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        public static string SubHomeViewModel_sponsors {
            get {
                return ResourceManager.GetString("SubHomeViewModel.sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY.
        /// </summary>
        public static string summery_ {
            get {
                return ResourceManager.GetString("summery_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomoor.
        /// </summary>
        public static string tomoor_ {
            get {
                return ResourceManager.GetString("tomoor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total_ {
            get {
                return ResourceManager.GetString("total_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDO.
        /// </summary>
        public static string undo_ {
            get {
                return ResourceManager.GetString("undo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string UserAccountViewModel_adresses {
            get {
                return ResourceManager.GetString("UserAccountViewModel.adresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string UserAccountViewModel_logout {
            get {
                return ResourceManager.GetString("UserAccountViewModel.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Logout ?.
        /// </summary>
        public static string UserAccountViewModel_logoutMsg {
            get {
                return ResourceManager.GetString("UserAccountViewModel.logoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string UserAccountViewModel_Orders {
            get {
                return ResourceManager.GetString("UserAccountViewModel.Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string UserAccountViewModel_pesonalData {
            get {
                return ResourceManager.GetString("UserAccountViewModel.pesonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Address.
        /// </summary>
        public static string UserAdressesViewModel_AddAdresses {
            get {
                return ResourceManager.GetString("UserAdressesViewModel.AddAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string UserAdressesViewModel_adresses {
            get {
                return ResourceManager.GetString("UserAdressesViewModel.adresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Address.
        /// </summary>
        public static string UserAdressesViewModel_adressesNotDel {
            get {
                return ResourceManager.GetString("UserAdressesViewModel.adressesNotDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this address ?.
        /// </summary>
        public static string UserAdressesViewModel_deleteAdresses {
            get {
                return ResourceManager.GetString("UserAdressesViewModel.deleteAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has been added.
        /// </summary>
        public static string UserAdressViewModel_adressAdded {
            get {
                return ResourceManager.GetString("UserAdressViewModel.adressAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has not been added.
        /// </summary>
        public static string UserAdressViewModel_adressNotAdded {
            get {
                return ResourceManager.GetString("UserAdressViewModel.adressNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has not been updated.
        /// </summary>
        public static string UserAdressViewModel_adressNotupdated {
            get {
                return ResourceManager.GetString("UserAdressViewModel.adressNotupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has been updated.
        /// </summary>
        public static string UserAdressViewModel_adressupdated {
            get {
                return ResourceManager.GetString("UserAdressViewModel.adressupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string userName_ {
            get {
                return ResourceManager.GetString("userName_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string WriteNewPasswordViewModel_code {
            get {
                return ResourceManager.GetString("WriteNewPasswordViewModel.code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code.
        /// </summary>
        public static string WriteNewPasswordViewModel_enterCode {
            get {
                return ResourceManager.GetString("WriteNewPasswordViewModel.enterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        public static string WriteNewPasswordViewModel_enterNewPassword {
            get {
                return ResourceManager.GetString("WriteNewPasswordViewModel.enterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string WriteNewPasswordViewModel_newPassword {
            get {
                return ResourceManager.GetString("WriteNewPasswordViewModel.newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Recoverd !.
        /// </summary>
        public static string WriteNewPasswordViewModel_notRecoverdMsg {
            get {
                return ResourceManager.GetString("WriteNewPasswordViewModel.notRecoverdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Account.
        /// </summary>
        public static string WriteNewPasswordViewModel_recover {
            get {
                return ResourceManager.GetString("WriteNewPasswordViewModel.recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovering completed.
        /// </summary>
        public static string WriteNewPasswordViewModel_recoverdMsg {
            get {
                return ResourceManager.GetString("WriteNewPasswordViewModel.recoverdMsg", resourceCulture);
            }
        }
    }
}
